#!/usr/bin/env bash
cd "$(dirname "$0")" || exit 1
OUT=/tmp/pc-finish.txt
: > "$OUT"
say(){ printf "\n===== %s =====\n" "$1" | tee -a "$OUT"; }

say "1. Is PapercubVision actually inside the built app?"
APP=$(find ~/Library/Developer/Xcode/DerivedData/Papercub-*/Build/Products/Debug-iphonesimulator -maxdepth 1 -name "*.app" | head -1)
ls "$APP/Frameworks" 2>/dev/null | grep -i papercub | tee -a "$OUT" || echo "(static — linked into the pod, not a separate framework)" | tee -a "$OUT"
find ~/Library/Developer/Xcode/DerivedData/Papercub-*/Build -name "PapercubVision.swiftmodule" 2>/dev/null | head -2 | tee -a "$OUT"
find ~/Library/Developer/Xcode/DerivedData/Papercub-*/Build -name "libPapercubVision.a" 2>/dev/null | head -2 | tee -a "$OUT"

say "2. Ignore the generated native dirs"
grep -q '^apps/mobile/ios' .gitignore 2>/dev/null || cat >> .gitignore <<'IGN'

# generated by `expo prebuild` — regenerate, never commit
apps/mobile/ios/
apps/mobile/android/
IGN
git rm -r --cached apps/mobile/ios >/dev/null 2>&1
echo "done" | tee -a "$OUT"

say "3. Commit"
git add -A
git -c user.name="Papercub" -c user.email="noreply@anthropic.com" commit -q -m "Drop expo-av; the native iOS build now compiles

expo-av is unmaintained and its Objective-C header imports
ExpoModulesCore/EXEventEmitter.h, which no longer exists in ExpoModulesCore 57.
It cannot build against this SDK and was failing the whole native build.

It turned out never to be imported — the reader mocks narration with a timer
and only mentioned expo-av in a comment about future work. Replaced with
expo-audio for when narration is actually wired.

With that removed the full native build succeeds: expo prebuild, pod install,
and xcodebuild for the simulator all pass with zero errors. This is the first
time the Vision module's Swift has been compiled at all.

Also gitignores apps/mobile/ios — prebuild regenerates it.

Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>" 2>&1 | tail -3 | tee -a "$OUT"
git log --oneline -3 | tee -a "$OUT"
git push -q origin scaffold && echo "pushed" | tee -a "$OUT"

say "4. Full stack check"
pnpm -r typecheck 2>&1 | tail -8 | tee -a "$OUT"
(cd services/worker && npx vitest run 2>&1 | tail -4) | tee -a "$OUT"
(npx vitest run --root packages/shared 2>&1 | tail -3) | tee -a "$OUT"

echo; echo "Wrote $OUT"
